microsoftgraph/msgraph-sdk-dotnet-core

README.md
src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/RetryHandlerTests.cs

Fixes #
- Retry on HTTP status 504 [#476](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/476)
- Update readme's status badge.
- Update RetryHandler tests to test 504 retries.

Retry handler to retry on HTTP status 504.

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml

Xamarin update requires us to use msbuild pack to create a NuGet
package.
On branch mm/supportXamarinPack
Changes to be committed:
modified:   pipelines/previewBuild.yml
modified:   pipelines/productionBuild.yml

Update from dotnet pack to msbuild pack

---

src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs
src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Middleware/Options/RetryHandlerOption.cs
src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/Options/RetrytHandlerOptionTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/RetryHandlerTests.cs

Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/441
- Maximum request retries will be based against the maximum retries time limit specified by the client, or the default maximum retries time limit value.
- If the the delay is greater than the maximum retries time limit specified, then there will be no request retry and the response will be returned. 
- Link to the Retry Handler design spec: https://github.com/microsoftgraph/msgraph-sdk-design/pull/18

Updating Retry Handler to use time limit instead of count limit

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseClient.cs
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs

- Adds a new IHttpProvider to enhance compatibility with GraphClientFactory by working towards adding support for the following scenario.
```
HttpClient client = GraphClientFactory.Create(...);
var graphServiceClient = new GraphServiceClient(client);
```
This means that one can easily use a custom httpClient with the request builders provided.
- Modifies checks in BaseRequests.cs to not authenticate the requests when the Provider is 
either SimpleHttprovider or HttpProvider  and when authprovider is present.
- Adds tests
- resolves a task in #27  
- is the predecessor for https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/221

Add SimpleHttpProvider for GraphClientFactory compatibility

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseClient.cs
src/Microsoft.Graph.Core/Requests/BatchRequest.cs
src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/IBaseClient.cs
src/Microsoft.Graph.Core/Requests/IBatchRequest.cs
src/Microsoft.Graph.Core/Requests/IBatchRequestBuilder.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestTests.cs

This PR closes #46 
Adds request builder for the batch endpoint to base client so that the following scenario is possible. Where we use the graphServiceClient to send out the batchRequest content like this: 
```cs
// Add batch request steps to BatchRequestContent.
BatchRequestContent batchRequestContent = new BatchRequestContent(batchRequestStep1, batchRequestStep2);
/* Use the Request builders :) */
BatchResponseContent returnedResponse = await graphServiceClient.Batch.Request().PostAsync(batchRequestContent);
/* Read the responses :) */
HttpResponseMessage firstResponse = await returnedResponse.GetResponseByIdAsync("1");
HttpResponseMessage secondResponse = await returnedResponse.GetResponseByIdAsync("2");
```
Rather than calling `PostAsync` of a httpclient like this:
```cs
// Send …
```

Add batch request builder to baseclient

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs

This PR closes #45
1. Adds overload to add steps using HttpRequestMessage to support a scenario like
```cs
HttpRequestMessage httpRequestMessage1 = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/v1.0/me/");
HttpRequestMessage httpRequestMessage2 = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/v1.0/me/calendars");
// Add batch request steps to BatchRequestContent.
BatchRequestContent batchRequestContent = new BatchRequestContent();
batchRequestContent.AddBatchRequestStep(httpRequestMessage1);
batchRequestContent.AddBatchRequestStep(httpRequestMessage2);
// Send batch request with BatchRequestContent. 
HttpResponseMessage response = await httpClient.PostAsync("https://graph.microsoft.com/v1.0/$batch", batchRequestContent);
```
2. Adds overload to …

BatchRequestStep enhancements

---

src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
tests/Microsoft.Graph.Core.XamarinAndroid.Test/Resources/Resource.designer.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs

Currently when the GraphClientFactory builds a middleware pipeline, it checks to see if a handler already has InnerHandler set.  If it is, it throws an exception.
This causes a problem for handlers that set a finalhandler by default in their constructor.  This is a fairly common pattern.
This PR changes the behaviour to simply overwrite any existing InnerHandler.  The idea is that if a developer provides 4 handlers explicitly in the array, then the pipeline should contain exactly just those 4 handlers plus the finalhandler.

Update pipeline building.

---

src/Microsoft.Graph.Core/Extensions/SerializerExtentions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Middleware/ChaosHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/ChaosHandlerOption.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/ChaosHandlerTests.cs

Added ChaosHandler middleware for simulating server failures
This example shows how to create a GraphServiceClient with the ChaosHandler in the pipeline
```csharp
var handlers = GraphClientFactory.CreateDefaultHandlers(authProvider);
handlers.Add(new ChaosHandler());
// Create a customized HttpClient based on these handlers
HttpClient client = GraphClientFactory.Create(handlers);
// Create a GraphServiceClient based on the HttpClient
var graphClient = new GraphServiceClient(client);
```
ChaosHandler can also be created with a customized set of known failures.
```csharp
var handler = new ChaosHandler(new ChaosHandlerOption()
{
KnownChaos = new List<HttpResponseMessage>()
{
ChaosHandler.Create429TooManyRequestsResponse(new TimeSpan(0,0,5)), …
```

Added ChaosHandler

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs

This PR closes #51 
1. Return ids on creating a batchRequestStep without providing one i.e. making a call like 
```cs
string userRequestId = batchRequestContent.AddBatchRequestStep(userRequest);
```
2. Allow de-serializing of responseContent to known type on getting response from ID
```cs
User user = await returnedResponse.GetResponseByIdAsync<User>(userRequestId);
```
This therefore means a user can perform the following scenario and its variants
```cs
// Get request objects from graph
IUserRequest userRequest = graphClient.Me.Request();
IUserEventsCollectionRequest eventsRequest = graphClient.Me.Events.Request();
BatchRequestContent batchRequestContent = new BatchRequestContent();
// Add the batchRequest steps and get back the ids for the steps
var userRequestId = …
```

Batch Request Enhancements

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Serialization/Serializer.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs

This PR fixes microsoftgraph/msgraph-sdk-dotnet#587 and fixes microsoftgraph/msgraph-sdk-dotnet#291
- Updates method overload `DeserializeObject<T>(Stream stream)` in Serializer to use common serializer settings
- Uses common serializer for intermediate de/serialization in BatchRequestContent and BatchResponseContent to fix inconsistent responses as seen in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/587)
- Adds tests to validate date values are consistent before/after serialization for BatchRequestContent and BatchResponseContent

Use common serializer in Batch requests and responses

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs

Fixes #67
This PR undos the automatic setting of timeout property in the HttpClient that is passed in the constructor as the HttpClient could already have been used before to therefore cause an exception.
```cs
var httpClient = new HttpClient();
// make any request with the client
var graphServiceClient = new GraphServiceClient(httpClient); // no exception should throw!
```
No expection should be thrown on the last line of the example.

Prevent setting of timeout property in HttpClient

---

src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs

Fixes #70 , Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/605.
Allows a null httpClient to be set in the GraphServiceClient; unbreaks customers who don't use the authProvider and sets token on the request headers instead of using the authProviders.

null auth provider support

---

src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
src/Microsoft.Graph.Core/Requests/IResponseHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs

[Delta query](https://docs.microsoft.com/en-us/graph/delta-query-users?view=graph-rest-1.0) provides a way to track changes.  You begin to track changes with a request like this:
`GET https://graph.microsoft.com/v1.0/users/delta?$select=displayName,givenName,surname`
`var userDeltaCollectionPage = await graphClient.Users.Delta().Request().Select("displayName,givenName,surname").GetAsync();`
Currently, a developer has to inspect the selected properties on each object in the page. The inspection requires first that they check that the selected properties are not null before getting the changed value. If the selected property is a primitive, then they can capture that value. If the selected property is an object, they must also inspect all of its property with a null check before capturing …

DeltaResponseHandler adds a delta response payload manifest to CollectionPage.AdditionalData

---

pipelines/validatePR.yml
src/Microsoft.Graph.Core/AuthConstants.cs
src/Microsoft.Graph.Core/Authentication/MsalAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Authentication/TokenCredentialAuthProvider.cs
src/Microsoft.Graph.Core/Authentication/TokenCredentials/IntegratedWindowsTokenCredential.cs
src/Microsoft.Graph.Core/Exceptions/AuthenticationException.cs
src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs
src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs
src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Graph.Core/Extensions/TokenCredentialExtensions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseClient.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Authentication/IntegrateWindowsTokenCredentialTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Authentication/TokenCredentialAuthProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/BaseRequestExtensionsTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockTokenCredential.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseClientTests.cs

1. Adds support for TokenCredentials from Azure.Identity by adding TokenCredential Auth provider.
Therefore one can make use a TokenCredential from Azure.Identity to make calls like the example below which uses the InteractiveBrowserCredential.
```cs
string clientId = "clientId";
string[] scopes = new[] { "User.Read", "Mail.ReadWrite" };
InteractiveBrowserCredential myBrowserCredential = new InteractiveBrowserCredential(clientId);
TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(myBrowserCredential, scopes);
//Try to get something from the Graph!!
HttpClient httpClient = GraphClientFactory.Create(tokenCredentialAuthProvider);
HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/v1.0/me/"); …
```

TokenCredential Support

---

pipelines/previewBuild.yml

I believe this is why we aren't seeing feature/2.0 preview builds kicking off.
Add feature/2.0 branch path spec.
@andrueastman

Update previewBuild.yml for Azure Pipelines

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BatchRequest.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Authentication/IntegrateWindowsTokenCredentialTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs

This pull request introduces the use of System.Text.Json for marshalling and unmarshalling of batch requests and therefore the change involves the replacement of Newtonsoft in the batch request code.
- As System.Text.Json still does not have a writable Json Dom(equivalents for JArray,JObject etc) the code involves the use of the Utf8JsonWriter to write out json in instances where json writing is needed.
- The previous tests that existed are unbroken by the change. This therefore validates that the functionality remains the same with the added benefits of System.Text.Json. 😄 
Making of batch requests remains the same and can be done as before as follows: - 
```csharp
// Create http GET request.
HttpRequestMessage httpRequestMessage1 = new HttpRequestMessage(HttpMethod.Get, …
```

Batch Requests with System.Text.Json

---

src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs

Fixes #93. The propertyValue of an array item can be a JObject or a JValue in the case of a primitive.
@andtu - It wasn't handling this:
"proxyAddresses": [
"SMTP:user@contoso.com"
],

Support JSON array of primitives

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml
pipelines/validatePR.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadResponseHandler.cs
src/Microsoft.Graph.Core/Serialization/InterfaceConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Authentication/IntegrateWindowsTokenCredentialTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/RetryHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadResponseHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadSliceRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/ITestEventDeltaCollectionPage.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestAttendee.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestBodyType.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDateTimeTimeZone.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDrive.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDriveItem.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEmailAddress.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEvent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionPage.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionResponse.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestItemBody.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestNotebook.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestRecipient.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestUser.cs

This PR migrates the DeltaResponseHandler to use System.Text.Json.
As a result the Newtonsoft dependency is now dropped from the project. 😄 
This PR also : -
- Adds a number of System.Text.Json compatible Test Models. 
This is done to drop the service library dependency that uses Newtonsoft causing a cyclic dependency on Newtonsoft and also to enable validation. (The models whould ideally be dropped once we have a compatible service library)
- Enables running of tests in the pipeline

DeltaResponseHandler with System.Text.Json

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs

Fixes #28
- Refactored SimpleHttpProvider and HttpProvider to enable the bubbling up of the TaskCancelledException for correct task management by client apps
- Updated tests to capture this 😃 
- https://stackoverflow.com/questions/47890382/periodic-timeout-exception-when-i-cancel-onedrive-task-that-reads-file-informati
- https://stackoverflow.com/a/47900445/987850

Fix for incorrect task cancellation

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs

This PR adds support for native http handler when targeting Xamarin.Mac (NSUrlSessionHandler)
#413 Cannot download multiple OneDrive files concurrently since v.1.13.0-beta

Support native plaform Http handlers for Xamarin.Mac

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs

Support mac http handlers

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/GraphResponse.cs
src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs
src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphResponseTests.cs

This PR adds support for the GraphResponse object which will act as a wrapper for properties like the status code and http headers.
This work is done according to the spec found here.
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphResponse.md
Currently, a user should be able to follow the following flow
```csharp
BaseClient client = new BaseClient(requestUrl, authenticationProvider, customHttpProvider);
BaseRequest baseRequest = new BaseRequest(requestUrl, client);
GraphResponse<TestUser> returnedResponse = await baseRequest.SendAsyncWithGraphResponse<TestUser>("string", CancellationToken.None);
TestUser user = await response.GetResponseObjectAsync();
```
Fixes [AB#4600](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4600 …

GraphResponse object

---

src/Microsoft.Graph.Core/Requests/Middleware/CompressionHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/CompressionHandlerTests.cs

Address [AB#4768](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/4768)
- CompressionHandler currently doesn't forward HttpContent headers to the next middleware in the chain. This change fixes that by copying the headers from the source HttpContent to the destination StreamHttpContent. 
- Adds tests to confirm custom and content headers are always copied after compression.

Compression header handling

---

scripts/IncrementPreviewVersion.ps1

Fixes error in incrementing preview version since we have to support both 1.x.x and 2.x.x incrementation of the preview version.

Fix preview increment

---

src/Microsoft.Graph.Core/Requests/BaseRequestBuilder.cs

This seems to be the only implementation of a RequestBuilder which doesn't have its corresponding interface?
This is part of a problem (also see https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/722) for anything use `BaseFunctionMethodRequestBuilder` as a RequestBuilder because it doesn't implement the interface and inherits from the base class directly here:
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/61405c1b8931dd6635b97f4e3ba68d81d56b13de/src/Microsoft.Graph.Core/Requests/BaseFunctionMethodRequestBuilder.cs#L13
Therefore things like the [`IDriveRecentRequestBuilder`](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/IDriveRecentRequestBuilder.cs)'s implementation is not compatible to case to a generic …

Add `IBaseRequestBuilder` interface to `BaseRequestBuilder` class

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml

Added new signing service connection, updated pipelines to support it. For future, we can just update the service connection as we store the cert in AKV. Validated that signing works with this new connection and cert.

Use new service connection

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

Fixes #120
- This PR fixes the exception thrown when creating a LargeFileUpload without specifying the slice size since the default value is not a multiple of 320KB
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/73
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/158

Fix DefaultMaxSliceSize in LargeFileUpload task

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs

Closes #113 
Essentially sometimes the contentype of an error response may be null causing us to fail to return the expected ServiceException

Fix for NullReference exception thrown when contentType is empty

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs

Fixes #165 
This PR adds support to Base Request for content types with parameters so that content types  like `application/json; odata=verbose` do not throw a Format Exception.
Test has been added to validate this change.

Add support for content type with parameters to BaseRequest

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphRequestContext.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/CaeAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/ICaeAuthenticationProviderOption.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs

This PR fixes #166
The PR involves extracting the claims property from WwwAuthenticate headers from 401 responses. The claims property is then Base64 decoded before being placed in the GraphContext through the `AuthenticationHandlerOption` property.
Placing the claims in the GraphContext will then enable the relevant AuthProviders to read the claims property and use it during the Authentication phase.
Related Links
- #166
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/pull/91

Add Continuous Access Evaluation (CAE) support

---

.github/dependabot.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/GraphRequestContext.cs
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/CaeAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/ICaeAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.Core.XamarinAndroid.Test/Microsoft.Graph.Core.XamarinAndroid.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

This PR creates a new release for the core library with the following fixes
- Dependabot updates(#148,#149,#150,#151,#153,#154,#156)
- Fix for NullReference exception thrown when contentType is empty (#164)
- Fix DefaultMaxSliceSize in LargeFileUpload task (#159) 
- Add support for content type with parameters (#169)
- Add Continuous Access Evaluation (CAE) support (#173)

1.23.0 release

---

.github/dependabot.yml
pipelines/previewBuild.yml
pipelines/productionBuild.yml
pipelines/validatePR.yml
scripts/IncrementPreviewVersion.ps1
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/BaseRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Requests/GraphRequestContext.cs
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/CompressionHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/CaeAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/ICaeAuthenticationProviderOption.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/CompressionHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

This PR syncs changes made in the dev branch to the feature/2.0 by cherrypicking relevant commits to the dev branch since the last sync (i.e 1.20.0 release)
The relevant PRs/commits include 
- #101 Fix typo
- #110 Support Mac Http handlers
- #118 Compression header handling
- #121 Fix Preview increment script
- #130 Use new service connection in pipelines
- #146 Create dependabot.yml
- #159 Fix DefaultMaxSliceSize in LargeFileUpload task 
- #164 Fix for NullReference exception thrown when contentType is empty
- #169 Add support for content with parameters
- #173 Add continuous access evaluation(CAE) support
**Exceptions**
- Dependabot PRs (i.e.#156, #153, #149, #150, #148 ,#151 and #154) have been skipped as dependabot will create PRs separately in the future.
- PR #135 has been skipped …

Sync dev and 2.0 branch

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/ODataMethodBooleanResponse.cs
src/Microsoft.Graph.Core/Models/ODataMethodInt32Response.cs
src/Microsoft.Graph.Core/Models/ODataMethodInt64Response.cs
src/Microsoft.Graph.Core/Models/ODataMethodStringResponse.cs
src/Microsoft.Graph.Core/Serialization/Serializer.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR completes the work of synchronizing the dev and feature/2.0 branch started off in #182 
It involves the refactoring of the work done in #135 to a System.Text.Json implementation needed in the 2.0 pipeline.
**Links**
- #135 
- #134 
Fixes #185

Fixes deserialization of OData primitive types (feature 2.0)

---

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR involves : -
- Changing Flush method calls to the async versions in the BatchRequestContent.cs
- Fixing incorrect deserialization from abstract parent types. When using the DerivedTypeConverter, this would lead lead to extra properties of the child class being put in the additional data rather than being deserialized to the correct properties.
The change involves using the derived types properties rather than the parent type properties.

Polymorphic deserialization fix

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseFunctionMethodRequestBuilder.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestBuilderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ComposableFunctionRequestBuilder0.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ComposableFunctionRequestBuilder1.cs

This was already reviewed in #183 
* Parameter string is now set before the Request method is called. The generator must now support `SetFunctionParameters()` after parameters are set in a request builder.
* Update BaseFunctionMethodRequestBuilder
- Remove the setting of parameters in Request. This is now done in `SetFunctionParameters()` in the generated request builders.
- Removed unused code. passParametersInQueryString was never set (always true) and the query options were only ever set via CreateRequest(). Definitely need another set of eyes on this.
- We want composable functions to always emit with parenthesis to distinguish from cast syntax. This is a change as functions without parameters weren't emitting parens. `SetFunctionParameters()` has to be called for each function …

Release: Support composable functions from the generated service library

---

src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs

This PR:-
- Fixes #193.  Sets response headers in ServiceException so that customers have access to correlation ids  
- Fixes #188 . Prevents potential deadlock from occurring when `AuthenticateRequestAsync(request)` is called.

Fix for potential deadlock on Authentication

---

src/Microsoft.Graph.Core/Requests/ResponseHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphResponseTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs

This PR closes #206.
With the introduction of GraphResponse, customers now have a way to access the Http Response Headers and Http Response Status Code. 
This PR therefore undoes the workaround earlier implemented that puts this info into the AdditionalData to improve performance and memory usage by deserializing the data directly from a content stream.

Update ResponseHandler to remove serialization headers and statusCode into AdditionalData 

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/Serializer.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR updates the Serializer to handle empty streams the same way it would handle empty strings to return default objects.
Tests have been added to validate this behaviour as well.

Handle empty streams similar to empty string content

---

src/Microsoft.Graph.Core/CoreConstants.cs

This moves the http method constants from the service library to core following discussion https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/905

Add http method constants

---

src/Microsoft.Graph.Core/CoreConstants.cs
src/Microsoft.Graph.Core/Extensions/SerializerExtentions.cs
src/Microsoft.Graph.Core/HttpMethods.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/BatchRequest.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Requests/HttpProvider.cs
src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequest.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/HttpRequestMessageExtensionsTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphResponseTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadResponseHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadSliceRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaRequest.cs

This PR closes #217 
It involves the changing of the Method type from string to enum to prevent erroneous inputs and provide central references. 
This PR also replaces the inline use of string values for "application/json" and "application/octet-stream" with Constants provided in the CoreConstants file.
The aim is to use these constants in the service library using central references from the core library to prevent redefinitions of constant values.
Related 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/905

Change Method type in IBaseRequest to enum

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml
scripts/GetNugetPackageVersion.ps1
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

Fixes #126 
Related to: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/247
Related to: https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/937
- Bumped minor version
- Added `msbuild` flags to generate symbols (see #227 for the `dotnet cli` blocker)
- Changed singing filter to include both nupkg and snupkg files
- Changed file filter to extract a single file for version information
- Updated csproj to allow sourcelink

Add source link to enable debugging of our NuGet package

---

docs/logging-requests.md

This PR is aimed at providing a central, consistent, and quick reference/guidance for users of the SDK who wish to log requests made by the SDK. 
This is especially helpful if more information is required when we need to isolate/identify issues that may be going wrong with the SDK,
This is aimed providing a to give users if this is needed.

Logging handler guidance

---

src/Microsoft.Graph.Core/Serialization/DateTimeOffsetConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR closes #232 
This fixes the serialization of DateTimeOffset objects to no longer be culture dependent to emit consistent values for the strings accoring to the ISO 8601-1:2019 format

Fix for culture dependent DateTimeOffset serialization.

---

src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/236
Essentially, the current implementation of the DerivedTypeConverter would serialize properties in the AdditionalData bag as a nested property called 'AdditionalData'. (This would only affect serialization of classes using this converter).
This is now resolved in this PR and validated in the tests.
Thanks for raising this @baywet

Fix DerivedTypeConverter serialization with JsonExtensionDataAttribute(AdditionalData)

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/EnumTypeWithFlags.cs

This PR closes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/267
It involves updating the System.Text.Json dependency to resolve an issue where the naming policy was not applied accross enum values which are Flags. See https://github.com/dotnet/runtime/issues/31622
A test has been added to validate that the upgrade does indeed fix the issue.

Update System.Text.Json dependency to fix naming policies application to [Flags] enums

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml
scripts/GetNugetPackageVersion.ps1
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

This PR completes the work set out in #239 
It involves the synchronization of work done in the [1.25.1 release](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/releases/tag/1.25.1) with the 2.0 branch.
The commits/PRs synchronized from the dev branch are
- #228 - Add source link to enable debugging of our NuGet package
- #230 - Change debug type to portable 
Sample artifacts can be found [here](https://o365exchange.visualstudio.com/O365%20Sandbox/_build/results?buildId=5000677&view=results)

Sync 1.25.1 release changes with 2.0 branch

---

src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/DateTestClass.cs

This PR is aimed at improved performance of the DerivedTypeConverter. 
Instead of catching the KeyNotFoundException when the "odata.type" is missing from the payload, we can use the TryGetProperty method to avoid the extra overhead of exception handling.
It also adds support to the DerivedTypeConverter to ignore properties with the JsonIgnore Attribute which will be useful in the event our public models are extended but still use the converter. This will enable the prevention of serializing new public properties added.
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/955

Use TryGetProperty method rather than catching of KeyNotFoundException in DerivedTypeConverter

---

src/Microsoft.Graph.Core/Requests/Middleware/Options/RetryHandlerOption.cs
src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/Options/RetrytHandlerOptionTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/RetryHandlerTests.cs

This PR closes #190 
When a user specifies the custom delegate `ShouldRetry` in the RetryHandlerOption.cs the delegate will not be respected if the request does not respect the conditions set out in the `ShouldRetry` private method [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/ba5eb6825f9de8e12707907ade8d548314688574/src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs#L192).  This is in turn leads to the result that users can only filter out requests to be retried rather than filtering in more options to be retried.

Fix for Request().WithShouldRetry is not called

---

src/Microsoft.Graph.Core/Serialization/TimeOfDayConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/TimeOfDayConverterTests.cs

This PR closes #244
It involves the updating of the TimeOfDayConverter to more lenient deserialization by using .NETs `DateTime.Parse` method rather than System.Text.Json underlying serializer which strictly expects ISO 8601-1:2019 date format by default

Fix deserialization of timeofday with leading zeros

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

This PR Specifies the System.Net.Http version in .Net45 in the Microsoft.Graph.Core.csproj.
This is meant to address warnings raised by dependabot.

Specify System.Net.Http version in .Net45

---

src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/DerivedTypeClass.cs

This PR modifies the DerivedTypeConverter to use the string value provided in the `JsonPropertyName` attribute to match properties during deserialization. 
This was initially done using the Property name in the object and therefore properties would sometimes be put into the additional Data rather than being put into the property since the names would not match.
Related issue:
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/291

JsonPropertyName attribute to match property names

---

src/Microsoft.Graph.Core/Requests/BaseRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestTests.cs

This PR involves adding the functionality to encode the query parameters of requests made through BaseRequest.
This is to ensure that special characters that appear in this section of the URL(such as ?,#,+) are URL encoded as they do not carry a special functions and therefore need to be encoded.
This PR also fixes the unnecessary addition of the query parameters with no data as outlined in #248

Encode url query data parameters

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/258
Currently, using the `HeaderOption` sets the headers of the HttpRequestMessage rather than what the batch code currently expects i.e. the `ContentHeaders`. 
This PR therefore updates the batch code to read the headers from the HttpRequestMessage itself as well so that headers in the HttpRequestMessage are also included in the sending of the batch request.

Include header options on sending batch request

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/253
It includes the US Government L5 (DOD) national cloud endpoint to the cloud list in GraphClientFactory.
Reference: -
https://docs.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints

Include US Government L5 (DOD) national cloud endpoint

---

src/Microsoft.Graph.Core/Exceptions/Error.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Exceptions/ErrorTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/100
In the event that the error response from graph has an unexpected property set in the payload as null, this causes NullReferenceException as the code tries to call the ToString method on a null value. 
The change therefore ensures that the SDK user will get the full error information and not hindered by the null reference exception in this case.

Fix for null reference on error property in some error payloads

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/728
Currently, SDK users are not able to access stream contents of batch responses with the following call because the stream to the deserializer thus causing a JsonSerializationException. Furthermore, the parent HttpResponseMessage will already have been cleaned up/disposed.
```cs
/// this is incorrect and should not be used as the response is passed to the deserializer.
using var responseUserPhotoFile = batchResponse.GetResponseByIdAsync<Stream>("1");
```
This PR therefore adds the ability for the SDK user to access stream responses with proper cleanup of the parent HttpResponseMessage being performed using the following call together with the relevant checks for error responses.
```cs
using var responseStream = …
```

Add support for accessing stream contents in batch requests.

---

src/Microsoft.Graph.Core/Requests/BaseRequest.cs

This PR closes #267 
SDK users running on .Net framework can experience deadlocks without the change below as outlined in the issue #267.

Fix for potential deadlock in .Net framework clients

---

src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs
src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/BaseRequestExtensionsTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs

This PR resolves feedback from https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/271
Currently we use `typeof(T).ToString()` to add/retrieve values from the `Middlewares` collection which introduces a performance penalty. This PR replaces those calls with `nameof` to alleviate that.
References
- https://www.erikschierboom.com/2015/12/31/csharp6-under-the-hood-nameof
- https://stackoverflow.com/questions/6417763/efficiency-of-cs-typeof-operator-or-whatever-its-representation-is-in-msil/6417977#6417977

Replace typeof(T).ToString() with nameof()

---

.github/CODEOWNERS

I noticed that dependabot PRs didn't have any reviewers. Adding the people I think should be default reviewers on any PR in this repo.

- adds code owner configuration

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
src/Microsoft.Graph.Core/Serialization/InterfaceConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestUser.cs

The changes proposed in this PR involve
- Fixing the serialization of Interface properties by ensuring the JsonSerializerOptions intance is passed over to ensure consistent serialization with all types. 
- Fixing the DerivedTypeConverter to call the right  `JsonSerializer.Serialize` overload as the previous overload no longer supports a null `Type` parameter(See [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/jsonserializer-serialize-throws-argumentnullexception-for-null-type)).
- Adding/Updating tests to validate the above
Related issues.
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1084
- https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/329

Fix inconsistent serialization of interface properties

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionResponse.cs

**Background**
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/255 added support for the encoding of the query parameters in urls to fix issues arising from the use of special characters in QueryOptions. However, during paging, the `@odata.NextLink` property is returned from the api endpoint with space characters replaced with `+` which causes it to be encoded and result to errors. 
**Fix**
To fix this, the PR adds the new `NextLinkConverter` to the core library to fix the initialization of the nextLink property in collectionResponse objects by first decoding the relevant url(which will result in a url safe to encode like changing `+` to space representation).
The PR adds tests to validate that this is mitigated appropiately.
This PR should be followed by …

Url decode nextLink url string.

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestItemBody.cs

This PR fixes an issue reported with the emitting of null values during serialization when the `NextLinkConverter` attribute is added to a model using the `DerivedTypeConveter`.
This leads to Api side errors as some values are not allowed to be set as null.
Existing tests have been enriched to capture this edge case.
Related to https://stackoverflow.com/questions/68768713/odata-nextlink-error-in-sendmail-via-graph-library

Fix DerivedTypeConverter emitting null values with NextLinkConverter attribute

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs

This PR fixes an issue with the DeltaResponseHandler where in the event a property in the delta query response is an empty array, the property would be left out of the list of change properties as the loop does not get the chance to iterate through an empty list.
This PR also 
- Adds a valid test to validate this change
- Fixes a missing XML comment for the public NextLink converter class

Fix for deltaResponseHandler leaving out empty arrays

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs

This PR merges dev to master to for the 2.0.2 release
Changes include: -
- Dependabot update bumping Azure.Core from 1.17.0 to 1.18.0
- Fix for deltaResponseHandler leaving out empty arrays via #307

Release 2.0.4

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs

This PR closes #310 
It involves fixing the incorrect building of batch requests when the url contains the string 'beta'. 
As the code simply searched for the string `beta` rather than the url segment `\beta\` this would result in queries being truncated if they contained the string beta in another part of the url.
This PR also adds unit tests to validate that this is resolved.

Fix for batch request urls with the string beta

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/332
It changes the NextLink converter to only replace `+` character with `%20` in the query string as this is the only character that changes form during decoding/encoding and causes issues due to double encoding.
The previous approach seems to bring issues as decoding the entire URL causes issues with URL parsing when passed to BaseRequest. According to the OData spec [here](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752335) base request should ideally be splitting a URL string that is encoded as decoding character like # will result to incorect splitting causing part of the Query segment being placed …

Fix bug when NextLink URL contains # special character.

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs

This PR closes #345 
It resolves an issue with .Net Framework clients that may add a second '?` character to the url query due to the question mark being always prepended to the string, even if the string already starts with a question mark.
**Reference**
- https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.query?view=net-6.0#remarks

Fix for incorrect URL building in .Net Framework

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs
src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs

This PR updates the Kiota core dependencies and refactors the project to bring in the latest changes to rename HttpMethod to Method.

Rename HttpMethod to Method

---

src/Microsoft.Graph.Core/Models/IUploadSession.cs
src/Microsoft.Graph.Core/Models/UploadSession.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

This PR refactors the LargeFileUploadTask to be work with the kiota core libraries in conjuction with refactoring made in previous PRs. 
- Refactoring the  LargeFileUploadTask constructor to take an IParsable that is verified to be an uploadSession
- Refactoring relevant models
- Refactoring tests
**Notes**
- There is an open issue with regards to creating an uploadSession with the generated request builders [here](https://github.com/microsoft/kiota/issues/990).

[Kiota] LargeFileUpload task refactoring 

---

src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Requests/Middleware/OdataQueryHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/Options/ODataQueryHandlerOption.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/OdataQueryHandlerTests.cs

This PR adds an OData query handler to the middleware pipeline as the generated query parameters from Kiota lack the `$` sign when requests are sent out.
As much as this should not be a problem in OData 4.0 which no longer requires the `$` prefix some workloads on graph still do not support this and this middleware alleviates the errors that may arise from a missing `$` prefix by reinserting based on whether the query parameter is an OData query parameter.

Odata query handler

---

src/Microsoft.Graph.Core/Authentication/TokenCredentials/IntegratedWindowsTokenCredential.cs
src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/ChaosHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/CompressionHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
src/Microsoft.Graph.Core/Requests/ResponseHandler.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequest.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequest.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs

Some awaited tasks included ConfigureAwait(false) but many did not. One of these continuations that was missing the ConfigureAwait(false) seemed to be causing deadlocks in our use of the Graph API (when acquiring a token). This pull request adds ConfigureAwait(false) to _all_ awaited tasks.
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/267
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/188

Always ConfiguteAwait false on awaited tasks

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs

This PR closes #368 and closes #22 
Changes include: 
- Returning `default` in the event the HttpResponseMessage message is non existent when trying to deserialize a payload from batch
- Ensure all headers are passed to the HttpContent of httpResponseMessage as this resulted in incorrect Content-Type headers
- Update tests to cover these scenraios

Fix for BatchResponseContent.GetResponseByIdAsync nullref and incorrect content header for non json response

---

src/Microsoft.Graph.Core/Authentication/TokenCredentials/IntegratedWindowsTokenCredential.cs
src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseRequest.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs
src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/ChaosHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/CompressionHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs
src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
src/Microsoft.Graph.Core/Requests/ResponseHandler.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequest.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequest.cs
src/Microsoft.Graph.Core/Serialization/NextLinkConverter.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.Core.XamarinAndroid.Test/Microsoft.Graph.Core.XamarinAndroid.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR creates the 2.0.8 release
- Fix for missing configureAwait in tasks via #363
- BatchContent fixes for incorrect headers and null reference exception via #369
- HTTP/2 support via #364 
- Dependabot updates via #352 , #354 , #358, #362, #365, #366 ,#370

Release 2.0.8

---

.github/dependabot.yml

This Pr configures the feature/3.0 branch for automatic dependabot update from a private registry.

Configure dependabot for feature/3.0 branch

---

pipelines/validatePR.yml

Following updates to the `windows-latest` vmImage, to window server 2022 as detailed [here](https://github.com/actions/virtual-environments/issues/4856), the breaking changes come with the side effect of some of the build depenedencies missing to build the repository.
This PR installs the missing dependency in order to unblock updates to the dev branch witnessed in #378 and #379 by installing the missing android SDK tools to meet the Xamarin dependencies in the build process.

Fix pipeline after image update

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs
src/Microsoft.Graph.Core/Requests/BaseClient.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/IBaseClient.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseClientTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/RequestTestBase.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadSliceRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs

This includes the following changes;
- Adds an IBaseClient for extensibility with the service library
- Adds back the `ExtractSessionFromParsable` method for handling upload sessions for the LargeFileUploadTask to accept an IParsable for now.

Adds IBaseClient for extensibility

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

This PR updates the Kiota core library references to support the following changes;
- Added support for vendor specific content types
- Added support for 204 no content responses
- Fixes a bug where converting `RequestInformation` to `HttpRequestMessage` would sometimes fail

Update kiota dependencies

---

src/Microsoft.Graph.Core/Exceptions/Error.cs
src/Microsoft.Graph.Core/Exceptions/ErrorDetail.cs
src/Microsoft.Graph.Core/Exceptions/ErrorResponse.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/AsyncOperationStatus.cs
src/Microsoft.Graph.Core/Models/UploadSession.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/AbstractEntityType.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/DateTestClass.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/DerivedTypeClass.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestAttendee.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestChangeNotificationEncryptedContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestChatMessage.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDateTimeTimeZone.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDrive.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDriveItem.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEmailAddress.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEvent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionResponse.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventItem.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventsResponse.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestItemBody.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestNotebook.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestRecipient.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestResourceData.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestSubscription.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestUser.cs

This PR is part of https://github.com/microsoft/kiota/issues/1490
It refactors the code to be compatible with latest Kiota packages with the Optimization of the `GetFieldDeserializers` from `IParsable`

Upgrade Kiota packages for GetFieldDeserializers optimization 

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/IBaseClient.cs

This is part of https://github.com/microsoft/kiota-abstractions-dotnet/issues/12
Changes include: -
- Drop usage of default interface implementations

Changes target runtime to netstandard2.0

---

src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1252 and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/436 and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/114
Changes include : - 
- Using the new `JsonProperty.Deserialize` method from dotnet 6 to avoid unnecessary string allocations
- Improve the custom `PopulateObject` function to cache the `PropertyInfo` instances in a dictionary to reduce calls to `PropertyInfo.GetCustomAttribute` which is expensive according to https://github.com/dotnet/runtime/issues/44713
- Fix the `WithResponseHandler` extension method to target interface not class.

Performance improvements on Derived Type converter

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventsDeltaResponse.cs

This PR fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1376
Due to the shape of some of the collection models returned by actions/functions, some of the collection models may not necessarily contain the `NextLink` property. Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/231
Changes include : -
- Fix paging for instances where the nextLink is present in the `AdditionalData` bag.
- Added tests to validate the changes.

Fix null reference exception on delta paging

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/54
It adds support for passing a callback to process page items that is `async`. Tests have been update to cover the scenario.

Support for async callback in the PageIterator

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BaseClient.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadSliceRequestTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

This PR closes #450, closes #215 and closes #132
Changes include:
- Ensure all BaseClient constructors take an AuthProvider
- Add support for passing a cancellationToken to the LargeFileUploadTask to fully align with the spec.
- Adds tests to capture cancelled cancellationTokens

Require AuthProvider param for all BaseClient constructor and  LargeFileUpload spec alignment

---

src/Microsoft.Graph.Core/Requests/Middleware/AuthenticationHandler.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequest.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/AuthenticationHandlerTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1416 and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/458
- Fix the parsing of the `WWWAuthenticateHeader` to avoid passing extra characters to the base64 decode function.
- Ensure the `ContentType` header is set in `UploadSliceRequest.cs`
- Updates tests to cater for these scenarios.

Fixes claims parsing of WWWAuthenticate header in some scenarios.

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionResponse.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventsResponse.cs

Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/460
It refactors the PageIterator to cater for the updated NextLinkProperty name due to changes made in https://github.com/microsoft/kiota/pull/1739
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d2802c613bca9a5620542d86df469e4a277ae124/src/Microsoft.Graph/Generated/Models/ContactCollectionResponse.cs#L17

Use updated nextLink property for pageIterator

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1436
It removes the Argument Exception thrown when the LargeFileUploadTask is initialized with a slice size that is not a multiple of 320KB to allow for other scenarios like PrintDocument. 
This makes the LargeFileUploadTask more agnostic to the endpoints being uploaded to and leaves the failure of the task to the exception thrown by the API in the event of an incorrect slice size.
Tests have been updated to capture this as well.

Remove restriction on 320KB multiple restriction for the LargeFileUploadTask

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs

Fixes microsoftgraph/msgraph-sdk-dotnet#1449.
For Graph resources which end with `Request`, the model generator adds
the postfix `Object`. Since we use the ODataType to construct an
instance of the generated class in `DerivedTypeConverter`, we actually
attempt to create instances of the wrong type. To fix this, we also add
the postfix to the type name in `DerivedTypeConverter`, before
attempting to create instances of the type.

Add `Object` postfix to type name in `DerivedTypeConverter`

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1456
It fixes an issue with the WinHttpHandler initialization with proxy for .NetFramework clients as the `WindowsProxyUsePolicy` needs updating when a proxy is set. 
Reference for this is at 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L575

Fixes WinHttpHandler initialization with proxy for .NetFramework clients

---

src/Microsoft.Graph.Core/Exceptions/ServiceException.cs
src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

This PR includes a few improvements
Changes include:- 
- Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/174 by ensuring `ServiceException` implements `IParsable` similar to other error classes from Kiota.
- Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/317 by adding support for v2 tokens for the `ITokenValidableExtension`
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/318 by ensuring that target environments running net6.0 and above utilize the `SocketsHttpHandler` with the correct configuration to prevent stale DNS issues.

Http client resilience extensions updates

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs

Contributes to #438. Fixes #436 (for good?)
- Cache property mapping for all derived types of `T` in a static `ConcurrentDictionary`.
- Cache compiled factory delegates for all derived types of `T` in a static `ConcurrentDictionary`.
- Use `IsDefined` instead of `GetCustomAttribute` where the attribute itself isn't used.
I ran the following benchmark (using `BenchmarkDotNet`) to verify the optimizations:
```csharp
[MemoryDiagnoser]
public class Benchmarks
{
private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);
[Params(10, 100, 1000)] public int N;
private string JsonData;
[GlobalSetup]
public void GlobalSetup()
{
var statuses = Enumerable.Range(0, N).Select(i => new AsyncOperationStatus
{
Operation = "Operation" + i,
Status = "In progress", …
```

Cache property mapping in DerivedTypeConverter<T>

---

.github/workflows/validatePullRequest.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj

This PR creates the 2.0.14 release.
Changes include : 
- Dependabot updates via #512 , #516 and #517
- DerivedTypeConveter performance enhancements through property mapping caching via #519 (credit to @khellang )

Release 2.0.14

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs
src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs

This PR is part of https://github.com/microsoft/kiota/issues/1858
Depends on 
- https://github.com/microsoft/kiota-abstractions-dotnet/pull/41
- https://github.com/microsoft/kiota-http-dotnet/pull/44
- Updates dependencies and aligns code changes to breaking changes made in https://github.com/microsoft/kiota-abstractions-dotnet/pull/41 and https://github.com/microsoft/kiota-http-dotnet/pull/44 to set the responseHandler using the new APIs

Updates Kiota Dependecies for ResponseHandler updates

---

src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs

Fixes #
[Retry Handler actually wait time and returned does not match](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/525)

Delay should return the real wait time

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs

This PR includes MACCATALYST preprocessor directive to omit CompressionHandler that is already handler by the NSUrlSessionHandler
It also aligns other directives to the directives used in the codebase. 
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1551

Omit CompressionHandler in Macatalyst 

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs

Syncing the fix at https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/590 to the Kiota based branch

Disables WinHttpHandler internal timeouts(Kiota)

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs

This PR disables the timeouts in the `WinHttpHandler` used by clients targeting the .NetFramework. 
The default timeouts in `WinHttpHandler` of 30 seconds override the timeouts used by the HttpClient and therefore causes clients to be unable to configure the clients using the Timeout property provided by the client.
Also closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1580 so that the progress task reports the number of bytes uploaded so far.

Disables WinHttpHandler internal timeouts

---

src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContentCollection.cs
src/Microsoft.Graph.Core/Requests/Content/KeyedBatchResponseContent.cs

Fixes #612 
- Automatically splitting batch requests into multiple batches without the user having to manage it.
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/29
- https://github.com/svrooij/msgraph-sdk-dotnet-batching/ (same code, but implemented as extension)
- https://svrooij.io/2023/03/03/batching-in-microsoft-graph/#adding-users-with-batching-exception (describing issue)
As [promised](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/612#issuecomment-1453872641) to @maisarissi a PR with my extension code integrated in the Graph SDK for dotnet.

Proper Batching support

---

.github/dependabot.yml
.github/workflows/auto-merge-dependabot.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventsDeltaResponse.cs

Closes #619 
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/554
It fixes parsing of the deltaLink in the pageIterator as the deltaLink will not necessarily live in the additionalData but as a strongly typed property of the `BaseDeltaFunctionResponse` class.
Test models have been updated to capture this.

Fixes deltaLink parsing in PageIterator.

---

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContentCollection.cs

Fixes #621 
- Expose `GetResponsesStatusCodesAsync()` for **BatchResponseContentCollection** and **BatchResponseContent** that allows checking the status codes without creating **HttpResponseMessage** for each step (that has to be disposed)
- Expose `BatchRequestSteps` for **BatchRequestContentCollection** so you can possibly fetch the failed steps to retry, for instance in case of some `429` results in the batch.
- extra constructor for `BatchRequestContentCollection` including the number of requests that may be combined. (At the moment you cannot combine more then 4 requests, when creating TodoTasks, all above 4 fail with 429.) This allows the user to use batching without having to manage smaller batches himself.
- https://svrooij.io/2023/03/03/batching-in-microsoft-graph/
- Demo code …

feat: Allow checking statuscodes of batch response without parsing step body

---

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs

- Add `NewBatchWithFailedRequests` to both **BatchRequestContent** and **BatchRequestContentCollection** accepting the dictionary from `batchResponse.GetResponsesStatusCodesAsync()`
- Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1759
I don't know where the docs are, but maybe add something like this.
```csharp
var client = new GraphServiceClient(...);
var batch = new BatchResponseContentCollection(client, 20);
// Add steps here with
await batch.AddRequestStepAsync(....);
// Execute batch
var batchResponse = await client.Batch.PostAsync(batch);
// Get status codes
var responseStatuses = await batchResponse.GetResponsesStatusCodesAsync();
// Validate success
var success = responseStatuses.All(s => BatchResponseContent.IsSuccessStatusCode(s.Value));
// Retry failure …
```

feat: New batch for failed requests

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs

This PR 
- updates CI build pipelines to latest `EsrpCodeSigning` and `Credscan` tasks
Runs at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=111731&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9 and https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=111732&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c5f33a6e-0090-51d5-8ebe-807b6dc9ca94
- Bumps library version for new release.
- Updates the BatchRequestBuilder to accept `errorMapping` array to allow for consistent errors. Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1782

Updates CI pipelines and creates release.

---

.github/policies/msgraph-sdk-dotnet-core-branch-protection.yml

Initial commit [generated from the existing UI set branch policies using GH CLI](https://github.com/MIchaelMainer/policyservicetoolkit/blob/main/branch_protection_export.ps1). 
Carefully review the policy for additions and changes that should be added here. Review subsequent commits for changes to policy.

- add branch protection policy file

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseClientTests.cs

Depends on https://github.com/microsoft/kiota-http-dotnet/pull/120

Bumps http library version for base url fix.

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Helpers/UrlHelperTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/657
It fixes a bug where the values of the a single request would be added twice when being marshalled for verification. 
It also updates various tests to remove warnings after the update of the testing package via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/691

Fixes error on BatchRequestContentCollection.NewBatchWithFailedRequests after request is sent out

---

.github/workflows/validatePullRequest.yml

- bumps java version for sonarcloud to stay on supported version

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/UploadSession.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Serialization/SerializerTests.cs

Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2092
The uploadSession payload sometimes returns with a property values that are pascal cased. This PR adds a couple of function to the `UploadSession` deserializers to enable uploads to not stop due to missing information. 
cc @GeoffreyYue1

Fixes incomplete uploads due to properties mismatch

---

pipelines/previewBuild.yml
pipelines/productionBuild.yml

Fixes release pipeline to set Java Home to JDK 11 instead of JDK8 
References
- https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#java

Release pipeline fix

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

This PR updates `Microsoft.Kiota.Abstractions` to the latest version to create a new release.
This fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2251 and fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2260

Bump abstractions dependencies

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

Bumps abstractions http dependencies to fix `ActicitySource` memory leak when the HttpClientRequestAdapter does not construct the HttpClient internally.

Bump http library

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/ITokenValidable.cs

This PR 
- Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/792 by updating vulnerable version of the `Microsoft.IdentityModel.Protocols.OpenIdConnect` packages
- Partially addresses https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2237 by fixing the `IEnumerable` type to `List` in the `ITokenValidable` to align to kiota generated collections. 
- Bumps version for new package release

Fixes vulnerable JWT dependencies

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/ITokenValidable.cs

This PR creates the 3.1.5 release
Changes include : 
- Bumps JWT dependencies to sucurity vlunerability(https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/792).
- Fixes ITokenValidable interface to use kiota generated types.

Release 3.1.5

---

src/Microsoft.Graph.Core/Helpers/ReadOnlySubStream.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Models/ITokenValidable.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Helpers/ReadOnlySubStreamTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj

This PR creates the 3.1.6 release
- ReadOnlySubstream is seekable to be compatible with RetryHandler via #797 
- Dependabot updates via #795

Release 3.1.6

---

.github/workflows/validatePullRequest.yml
CHANGELOG.md
README.md
global.json
pipelines/productionBuild.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs
src/Microsoft.Graph.Core/global.json

Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/815
Add a new constructor to the `BatchRequestContentCollection` class to also take a `IRequestAdapter` to unlock scenarios using self serve.
Other changes include
- Adds CHANGELOG.md file to the repo for tracking changes made to the code.
- Updates the csproj file to exclude MAUI targets by for easier to local development and unlock dependabot updates(currently failing due to environment not installing them and should fix https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/801 ). These targets are still built in CI for the PR checks and release pipelines and can be built locally by running -`dotnet build p:IncludeMauiTargets=true`

Use `IRequestAdapter` in `BatchRequestContentCollection`

---

Directory.Build.props
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

Follow up to #818 
Dependabot is excluding the csproj as it can't find the TargetFrameworks tag. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/network/updates/806228013
Moves the `MauiTargets` to build.props file as is done in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Azure.Core.csproj#L11 to attempt to fix the dependabot issue.

Fixes dependabot updates #2

---

CHANGELOG.md
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs

Follow up to https://github.com/microsoft/kiota-dotnet/pull/303

fix: automatic decompression of response content

---

.github/policies/msgraph-sdk-dotnet-core-branch-protection.yml

ci: removes branch protection rule for old feature branch

---

src/Microsoft.Graph.Core/Authentication/AzureIdentityAuthenticationProvider.cs

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

fix: missing constructor for CAE

---

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs

Fixes #871 
- Adding optional parameter `requestId` to `AddBatchRequestStepAsync()` function to allow manual configiguration of requestId on BatchRequests (See reasoning on issue #871 for details)

feat: Add option to specify requestId manually when calling AddBatchRequestStepAsync()

---

src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

Fixes code scanning alerts on AAD issuer validation according to docs at https://identitydivision.visualstudio.com/DevEx/_wiki/wikis/DevEx.wiki/54311/Validate-the-AAD-key-issuer-if-you-use-IdentityModel-directly-to-validate-Azure-AD-tokens and alerts raised at https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/security/code-scanning

fix: Fixing code scanning alert on AAD issuer validation

---

pipelines/productionBuild.yml

Release please already creates a GH release so the release pipeline should simply edit this by uploading the artifacts to it.

ci: fixing double tagging and GH releases

---

src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs

- Removes encoding from batch request relative URIs
- Added unit test to ensure URIs are not encoded
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/discussions/2538
- Possibly related issue: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2089

fix: encoded batch request URI issue

---

.github/workflows/sonarcloud.yml
tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj

Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/904

ci: setup sonarcloud

---

.github/policies/msgraph-sdk-dotnet-core-branch-protection.yml
.github/workflows/sonarcloud.yml
.github/workflows/validatePullRequest.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockUploadSessionWithoutInterface.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Trimming/Microsoft.Graph.DotnetCore.Core.Trimming.csproj
tests/Microsoft.Graph.DotnetCore.Core.Trimming/Program.cs
tests/Microsoft.Graph.DotnetCore.Core.Trimming/global.json

This PR resolves all trimming warnings in the project 
- Adding relevant `DynamicallyAccessedMembers` attributes where necessarry and Removing calls of `object.GetType()` (as this results in unresolvable trimming warnings)
- Add a trimming validation project and add a validation build step in the pipeline.

fix: resolve trimming warnings in project

---

src/Microsoft.Graph.Core/Exceptions/ErrorConstants.cs
src/Microsoft.Graph.Core/Extensions/IParseNodeExtensions.cs
src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
src/Microsoft.Graph.Core/Tasks/PageIterator.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs

Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2661
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2660
Larger batch response is currently not validated for success status code due to the use of the `NativeResponseHandler`. 
This PR adds a validation of the same in the BatchRequestBuilder to ensure the reponse is valid for handling.

fix: resolved error handling of larger batch request message

---

README.md
src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Properties/AssemblyInfo.cs
src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
src/Microsoft.Graph.Core/Requests/Content/BatchResponseContentCollection.cs
src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
src/Microsoft.Graph.Core/Requests/GraphRequestContext.cs
src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs
src/Microsoft.Graph.Core/Requests/ResponseHandler.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Helpers/ReadOnlySubStreamTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/BaseClient.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockAccessTokenProvider.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Properties/AssemblyInfo.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/DateTestClass.cs

pending review & release of https://github.com/microsoft/kiota-dotnet/pull/430
part of https://github.com/microsoft/kiota-dotnet/issues/270

Add `create()` overloads to support adding Authorization handler to HTTP clients

---

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj

removes upper bound for http win handler following the discussions in https://github.com/microsoft/OpenApi.ApiManifest/pull/117

fix: removes upper bound on System.Net.Http.WinHttpHandler

---

pipelines/productionBuild.yml

closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/944

chore: Label release job in pipeline to comply with 1ES

---

.github/workflows/validatePullRequest.yml
src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchRequestContentTests.cs
tests/Microsoft.Graph.DotnetCore.Core.Trimming/Microsoft.Graph.DotnetCore.Core.Trimming.csproj
tests/Microsoft.Graph.DotnetCore.Core.Trimming/global.json

Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2774
Authentication provider is unnecessarilly invoked repeatedly to set the Auth header which is unnecessary in the batch message. In the event that the message isn't in the cash this can cause increased execution for a task that is unneeded.

Fixes authentication on every request when using the `AddBatchRequestStepAsync` overload
