microsoftgraph/msgraph-sdk-dotnet-core

pipelines/validatePR.yml
=> Disable notifications

src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/482.
=> Update GraphClientFactory to skip CompressionHandler on Xamarin.iOS.

src/Microsoft.Graph.Core/Extensions/SerializerExtentions.cs, src/Microsoft.Graph.Core/Requests/Middleware/ChaosHandler.cs, src/Microsoft.Graph.Core/Requests/Middleware/Options/ChaosHandlerOption.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs
This PR adds some few missing XML comments to public functions/classes. 
This involves no functional changes to the source and is intended to 
- improve customer experience with provided information 
- reduce warning observed during project builds.
=> Add missing XML comments to public functions/classes.

pipelines/productionBuild.yml
Update service connection for signing
=> Update productionBuild.yml for Azure Pipelines

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
=> Testing 2.0 CI/CD

pipelines/previewBuild.yml, pipelines/productionBuild.yml, pipelines/validatePR.yml
Update pool to 
Hosted Windows 2019 with VS2019
=> Update validatePR.yml for Azure Pipelines

pipelines/validatePR.yml, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Trying to fix tests in CI check.
Dummy change made in csproj to trigger CI build as well.
=> Remove hanging quote to fix CI

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/BaseFunctionMethodRequestBuilder.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BaseRequestBuilderTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ComposableFunctionRequestBuilder0.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ComposableFunctionRequestBuilder1.cs
This PR closes #185 
Its syncs the work done in #183 to the feature 2.0 branch.
=> Sync composable functions work with 2.0 branch

src/Microsoft.Graph.Core/Requests/BaseRequest.cs, src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs
This PR syncs the bugs fixed on the dev branch via PR #200 with the 2.0 branch
=> Sync PR #200 with 2.0 branch

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
This PR updates the csproj file with release notes of latest changes in the 2.0 branch.
=> Update csproj to capture release notes

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
This PR closes #219 
This comes in as a new requirement as 4.6.1 is coming to EOL soon.
=> Update minimum netframework to v4.6.2 in feature/2.0

src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs
Same change as https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/223
=> Update RetryHandler.cs - drain response before exception

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
=> Change debug type to portable

pipelines/previewBuild.yml, pipelines/productionBuild.yml, scripts/GetNugetPackageVersion.ps1, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Includes symbols for debugging.
=> Release 1.25.1

docs/logging-requests.md
This PR adds some improvements to the guidance provided through #233 
These are :- 
- specifying best practices on draining responses
- specifying best practices on logging handler placement
=> Logging handler guidance improvements

src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
- Make the Method attribute settable as described in the summary: `Gets or sets the HTTP method string for the request.`
- #218 changed the type from string to Enum in feature/2.0. For this a second PR would be necessary.
=> Make IBaseRequest Method settable

src/Microsoft.Graph.Core/Requests/IBaseRequest.cs
- As already mentioned in #251 this makes the Method attribute settable in feature/2.0
=> Make IBaseRequest Method attribute settable

pipelines/validatePR.yml, src/Microsoft.Graph.Core/Authentication/ScopedAuthenticationProviderOptions.cs, src/Microsoft.Graph.Core/Authentication/TokenCredentialAuthProvider.cs, src/Microsoft.Graph.Core/Authentication/TokenCredentials/IntegratedWindowsTokenCredential.cs, src/Microsoft.Graph.Core/Extensions/BaseRequestExtensions.cs, src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs, src/Microsoft.Graph.Core/Extensions/TokenCredentialExtensions.cs, src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/GraphResponse.cs, src/Microsoft.Graph.Core/Requests/HttpProvider.cs, src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs, src/Microsoft.Graph.Core/Tasks/PageIterator.cs
This PR resolves feedback from #271 in preparation for v2 release of the sdk
=> Resolves feedback from #271

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs, src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs
This PR updates the feature/3.0 branch to support the new changes supporting CancellationToken introduced via https://github.com/microsoft/kiota/pull/874
=> Updates Kiota Core dependencies

.github/dependabot.yml, .github/workflows/validatePullRequest.yml, src/Microsoft.Graph.Core/Exceptions/ServiceException.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs, src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Extensions/IDecryptableContentExtensionsTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockAuthenticationProvider.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/xunit.runner.json
This PR updates graph core to the latest kiota dependencies.
Changes include: - 
- Refactoring for work covered via https://github.com/microsoft/kiota/issues/1006
- Refactoring for work covered via https://github.com/microsoft/kiota/issues/411
- Refactoring tests to cater for upstream breaking changes
- Update `dependabot.yml` to use private registry for updates.
=> Update to latest Kiota dependencies

src/Microsoft.Graph.Core/Extensions/HttpRequestMessageExtensions.cs, src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs, src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/BaseClient.cs, src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs, src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs, src/Microsoft.Graph.Core/Tasks/PageIterator.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/PageIteratorTests.cs
This PR syncs relevant changes on the dev branch with the feature/3.0 branch,
Changes include:
- Cherry picking changes made in #369 
- Cherry picking changes made in #363 
- Making the `RequestAdapter` member in `BaseClient` virtual allow potential overriding. 
- Dependency updates
=> Sync dev changes with feature/3.0

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
This PR is part of https://github.com/microsoft/kiota/issues/1494
It creates a new release to support the request config revamp updates.
=> Request config revamp

README.md, docs/collections.md, docs/headers.md, docs/logging-requests.md, docs/overview.md, docs/readme.md, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/MockAuthenticationProvider.cs
This PR
- Updates the Kiota library dependencies to the latest version as well as updates the version to create a new release of the core lib
- Fixes out of date documentation on the feature/5.0 branch to align with the Kiota generated sdks
- Updates tests due to changes brought about from the library updates.
=> Update Kiota dependencies and documentation

src/Microsoft.Graph.Core/Authentication/AzureIdentityAccessTokenProvider.cs, src/Microsoft.Graph.Core/Authentication/AzureIdentityAuthenticationProvider.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
depends on https://github.com/microsoft/kiota-authentication-azure-dotnet/pull/54
=> - sets the defaults hosts for the authentication provider

.github/dependabot.yml, .github/fabricbot.json, src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/GraphResponse{T}.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs, src/Microsoft.Graph.Core/Tasks/PageIterator.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs
Resolves merge conflicts on merge of feature/3.0 to dev
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/602
=> Resolves merge conflicts on #602

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Creates the 3.0 release
Merge after https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/603
=> Release 3.0

src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs, src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Mocks/BaseClient.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/BatchRequestBuilderTests.cs
This PR resolves feedback on #602
=> Resolves feedback on #602

.github/workflows/validatePullRequest.yml, pipelines/previewBuild.yml, pipelines/productionBuild.yml, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs, src/Microsoft.Graph.Core/Requests/Content/BatchRequestContentCollection.cs, src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs
This PR creates the 3.0.5 release.
- CI/BatchRequestBuilder updates via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/637
- Batch Requests for failed requests via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/636
=> Release 3.0.5

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Bumps version to create new release
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1755
=> Include error information in request header instances

src/Microsoft.Graph.Core/Authentication/AzureIdentityAccessTokenProvider.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/655
=> Include graph.microsoft-ppe.com in token provider

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Bumps abstractions dependency to include fix via https://github.com/microsoft/kiota-abstractions-dotnet/pull/110
=> Bump abstractions dependency

src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs
- Fix typos in `LargeFileUploadTask`
=> Fix typos in `LargeFileUploadTask`

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/AsyncMonitor.cs, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/AsyncMonitorTests.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs
depends on https://github.com/microsoft/kiota-abstractions-dotnet/pull/139
https://github.com/microsoft/kiota-serialization-json-dotnet/pull/137
https://github.com/microsoft/kiota-serialization-form-dotnet/pull/75
https://github.com/microsoft/kiota-serialization-multipart-dotnet/pull/27
https://github.com/microsoft/kiota-serialization-text-dotnet/pull/108
https://github.com/microsoft/kiota-http-dotnet/pull/155
https://github.com/microsoft/kiota-authentication-azure-dotnet/pull/131
=> - enables trimming

.github/workflows/validatePullRequest.yml
=> Fix codeQl permissions

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
=> Remove unneeded PackageReference

Directory.Build.props, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
The parameter needs a default value according to the tests from the dependabot source.
- https://github.com/dependabot/dependabot-core/blob/e05bd1923e6eec8346415396802a813805f1d312/nuget/spec/dependabot/nuget/file_parser_spec.rb#L644
- https://github.com/dependabot/dependabot-core/blob/e05bd1923e6eec8346415396802a813805f1d312/nuget/spec/dependabot/nuget/file_parser_spec.rb#L718
Otherwise, it will be identified as unresolvable.
This has been validated using the fork of the repo at https://github.com/andrueastman/msgraph-sdk-dotnet-core/pull/3
=> Fixes dependabot updates #3 

.github/workflows/project-auto-add.yml
=> chore: replaces project bot token task by official one

CHANGELOG.md, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Fixes generation due to lower abstraction dependency.
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=154944&view=logs&j=0c914960-8b50-5299-c9aa-dd3c9595168e&t=3b0ef9b7-0b0d-5874-6c1c-de7c5a8ae365
=> Updates base version for generation updates

CHANGELOG.md, src/Microsoft.Graph.Core/Authentication/AzureIdentityAccessTokenProvider.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
Follow up to https://github.com/microsoft/kiota-dotnet/pull/322
=> Changes to enable CAE by default. 

pipelines/productionBuild.yml
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/867
Todo
=> ci: upgrades esrp sign tasks

README.md
Tests validation of main branch as well release please
=> docs: Fixes broken link in readme

src/Microsoft.Graph.Core/Extensions/ITokenValidableExtension.cs, src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs, src/Microsoft.Graph.Core/Requests/ResponseHandler.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadResponseHandler.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSessionRequestBuilder.cs, src/Microsoft.Graph.Core/Requests/Upload/UploadSliceRequestBuilder.cs, src/Microsoft.Graph.Core/Tasks/PageIterator.cs, tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadResponseHandlerTests.cs
=> fix: corrects async suffixes where wrongly used

pipelines/productionBuild.yml
Fixes failing CI after addition of trimming project in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/903
=> ci: fix failing deploy after trimming project addition.

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
=> chore: upgrades MS identity model deps

pipelines/productionBuild.yml
ci: fix release pipeline dotnet version
Follow up to changes in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/956
=> ci: fix release pipeline dotnet version

src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj, src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/966
Follow up to similar PR at https://github.com/microsoft/kiota-dotnet/pull/512
=> fix: ensures valid handler is returned in browser scenarios
